build:
  nodes:
    analysis:
      dependencies:
        before:
      environment:
        php:
          version: 7.4
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      environment:
        php:
          version: 7.4
      tests:
        override:
          - command: (cd src/ && ./vendor/bin/codecept build && ./vendor/bin/codecept run --coverage-xml -v)
            coverage:
              file: src/tests/_output/coverage.xml
              format: clover

filter:
    paths: ["src/Ubiquity/*"]
    excluded_paths:

checks:
    php:
        code_rating: true
        duplication: true
